### ISSUE TITLE
Incorrect links in 04-error_analysis

### ISSUE THREAD

**Issue by ThomasHepworth** [OlivierBinette/er-evaluation#15]
It looks as if the links to `er_evaluation.error_analysis` within the [04-error_analysis](https://er-evaluation.readthedocs.io/en/latest/04-error_analysis.html#id3) section of your docs are incorrect.

I'm assuming it's supposed to point to the [API documentation](https://er-evaluation.readthedocs.io/en/latest/er_evaluation.error_analysis.html#module-er_evaluation.error_analysis)?

**Comment by OlivierBinette** [comment]
Fixed, thank you!
