### ISSUE TITLE
Editorial comment on JOSS submission

### ISSUE THREAD

**Issue by osorensen** [OlivierBinette/er-evaluation#18]
We see

```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1126/sciadv.abi8021 is OK
- 10.14778/3137628.3137642 is OK
- 10.1145/3418896 is OK

MISSING DOIs

- 10.1080/00031305.2023.2191664 may be a valid DOI for title: Estimating the Performance of Entity Resolution Algorithms: Lessons Learned Through PatentsView.org

INVALID DOIs

- None
```

Could you please check, and add the DOI if it is correct?

https://github.com/openjournals/joss-reviews/issues/5619

**Comment by osorensen** [comment]
In addition to the missing DOI pointed out be the editorialbot, please also add DOIs to the two arXiv preprints highlighted below. You find the DOIs on the arXiv website of the articles.

<img width="772" alt="image" src="https://github.com/Valires/er-evaluation/assets/21175639/08bcd9c0-e2d4-4598-a989-515ed247b56d">

**Comment by OlivierBinette** [comment]
@osorensen Thank you for your comments. I have updated the bibliography with DOIs.

**Comment by osorensen** [comment]
@editorialbot generate pdf

**Comment by osorensen** [comment]
@editorialbot check references

**Comment by osorensen** [comment]
Sorry, I wrote those comments in the wrong thread. Thanks for fixing!
